<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Storage Disk
    |--------------------------------------------------------------------------
    |
    | The filesystem disk used to store uploaded media files.
    |
    */
    'disk' => env('MEDIA_DISK', 'public'),

    /*
    |--------------------------------------------------------------------------
    | Storage Directory
    |--------------------------------------------------------------------------
    |
    | The base directory within the disk where media files are stored.
    |
    */
    'directory' => env('MEDIA_DIRECTORY', 'media'),

    /*
    |--------------------------------------------------------------------------
    | Collections
    |--------------------------------------------------------------------------
    |
    | Define the available media collections. Keys are stored in the database;
    | labels are shown in the UI and can be passed through __() for translation.
    |
    | Set `cover => false` on a collection that holds non-image media (e.g. video
    | embeds or documents). The admin then hides its "Use as cover image" toggle
    | and the schema refuses to persist that collection as the cover — an embed
    | URL is never a valid <img> source. Omit the key (or set true) for image
    | collections.
    |
    | Set `types => [...]` to restrict which media types a collection accepts —
    | e.g. `types => ['embed']` on a video collection, so the admin offers only
    | a player URL and an editor can't upload a file into a slot that expects
    | one. Omit the key to allow all three types.
    |
    */
    'collections' => [
        'images' => [
            'label' => 'Images',
        ],
        'documents' => [
            'label' => 'Documents',
            'cover' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Image Variants
    |--------------------------------------------------------------------------
    |
    | Resized WebP copies of every uploaded image, generated by the queued
    | `GenerateImageVariants` job when a row is created or its `path` changes,
    | and served through `Media::srcset()` / `Support\ImagePayload`.
    |
    | `widths` is the ladder: one rung per width, only rungs NARROWER than the
    | source are produced (never upscaled). Rungs live beside the original as
    | `{stem}-w{width}.webp`. `<img src>` stays the original — WebP-only rungs
    | are safe because the original is always the last-resort candidate.
    |
    | `max_megapixels` bounds time and disk. Memory is bounded separately, at
    | run time: the job estimates `pixels × bytes_per_pixel` against what is
    | still free under the worker's `memory_limit`. 8 is measured, not
    | derived: GD truecolor is 4 bytes per pixel and a bare `php -r` decode of
    | a 35.6 MP JPEG peaks at 140 MB, yet the same decode inside a booted
    | 256M worker with 198 MB free exhausted the limit (staging, 2026-09-04)
    | — so the real in-process cost is above 5.5 bytes per pixel. At 8, a
    | 256M worker skips anything past ~24 MP. Either bound records a skip
    | (`variants = {}`); neither ever decodes.
    |
    | `enabled => false` stops the dispatch altogether — for a consumer with no
    | queue worker. Both consumers run one today.
    |
    */

    'variants' => [
        'enabled' => (bool) env('MEDIA_VARIANTS_ENABLED', true),
        'widths' => [400, 800, 1600],
        'quality' => 80,
        'max_megapixels' => 40,
        'bytes_per_pixel' => 8,
    ],

    /*
    |--------------------------------------------------------------------------
    | Models
    |--------------------------------------------------------------------------
    |
    | Override the default models used by the Media domain. Each value
    | must be a class that extends the corresponding base model.
    |
    */

    'models' => [
        'media' => InOtherShops\Media\Models\Media::class,
        'mediable' => InOtherShops\Media\Models\Mediable::class,
    ],
];
